### ISSUE TITLE
Configure and export ThemeProvider

### ISSUE THREAD

**Issue by srdjanRakic** [inplayer-org/inplayer-ui#14]
Configure ThemeProvider to accept custom theme as prop or use the default as fallback.

**Comment by andrej-naumovski** [comment]
Will be resolved with commit https://github.com/inplayer-org/inplayer-ui/pull/15/commits/9d1ca1ce93edf6f745f57bdc2c56bd1d486b5937 of https://github.com/inplayer-org/inplayer-ui/pull/15.
